spring.application.name=UmbrellaGames

spring.datasource.url= jdbc:mysql://localhost/Umbrella_Games
spring.datasource.username = root
spring.datasource.password = 

#JPA
spring.jpa.hibernate.ddl-auto = update

#SQL
spring.jpa.show-sql = true
server.port = 8080
