INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (1,     3, "Assassin's Creed Brotherhood", 	"Ubisoft", 		            "assassin's creed brotherhood - capa1.png", 	59.99,		8.9, 		"é um jogo de ação e aventura em mundo aberto que dá continuidade direta à história de Assassin's Creed II, com o lendário Mestre Assassino Ezio Auditore da Firenze");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (2,     7,	"Borderlands2", 					"Gearbox Software", 		"borderlands 2 - capa1.png", 					44.99,		10, 		"Borderlands 2 é um looter-shooter de ação e RPG focado em quatro novos Vault Hunters lutando para libertar o planeta Pandora do ditador Handsome Jack, CEO da Hyperion Corporation.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (3,     7,	"Counter-Strike 2",					"Valve",					"counter-strike 2 - capa1.png",					0,			8.7,		"Counter-Strike 2, também conhecido como CS2, é um jogo tático multijogador de tiro em primeira pessoa anunciado em 22 de março de 2023 e lançado em 27 de setembro de 2023.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (4,     5,	"Disco Elysium",					"ZA/UM",					"Disco Elysium - capa1.png",					75.49,		10,			"Disco Elysium - The Final Cut é um RPG de detetive isométrico e focado em narrativa, onde você controla um policial amnésico e alcoólatra tentando resolver um assassinato em Martinaise");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (5,     2,	"Elden Ring",						"FromSoftware",				"elden ring - capa1.png",						274.50,		9.5,		"Elden Ring é um RPG de ação de mundo aberto desenvolvido pela FromSoftware, ambientado nas Terras Intermédias após a destruição do Anel Prístino (Elden Ring). O jogador controla um Maculado ");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (6,     2,	"Fallout: New Vegas",				"Obsidian Entertainment",	"fallout new vegas - capa1.png",				39,			9.7,		"Fallout: New Vegas (2010) é um RPG pós-apocalíptico onde você joga como Courier (Entregador), que sobrevive a uma tentativa de assassinato após ser baleado na cabeça.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (7,     6,	"Garry's Mod",						"Facepunch Studios",		"garry's mod - capa1.png",						25.99,		9,			"Garry's Mod (GMod) é um jogo sandbox de física sem objetivos pré-definidos, desenvolvido por Garry Newman.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (8,     4,	"Hollow Knight",					"Team Cherry",				"hollow knight - capa1.png",					46.99,		10,			"Hollow Knight é um jogo de ação e aventura metroidvania 2D no qual você controla um pequeno cavaleiro sem nome explorando o vasto e arruinado reino subterrâneo de Hallownest.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (9,     5,	"Inscryption",						"Daniel Mullins Games",		"inscryption - capa1.png",						49.99,		8.7,		"Inscryption é uma odisseia sombria de cartas que mistura terror psicológico, elementos de roguelike e quebra-cabeças escape room.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (10,    8,	"Journey",							"thatgamecompany",			"journey - capa1.png",							43.99,		8.8,		"Journey é uma parábola interativa e contemplativa, onde um viajante encapuzado atravessa um vasto deserto em direção a uma montanha sagrada.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (11,    1,	"Left 4 Dead",						"Valve",			        "Left 4 dead.png",							    2,99,		8.8,		"Left 4 Dead é um jogo de tiro cooperativo (co-op) focado em sobrevivência zumbi, onde quatro personagens tentam escapar de um apocalipse causado pela Gripe Verde");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (12,    1,	"Left 4 Dead 2",					"Valve",					"Left 4 dead 2.png",					        15,99,		10,			"Left 4 Dead 2 é um jogo de tiro cooperativo de terror que segue outros quatro sobreviventes lutando contra hordas de zumbis no sul dos EUA.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (13,    7,	"Half-Life",						"Valve",				    "Half-Life.png",                                274.50,		9.5,		"Half-Life (1998) acompanha Gordon Freeman, um físico teórico no complexo secreto de Black Mesa, que acidentalmente abre um portal dimensional para o mundo alienígena Xen durante um experimento falho.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (14,    1,	"Dota 2",				            "Valve",	                "Dota 2.png",				                    0,			9.7,		"Dota 2 é um jogo eletrônico do gênero multiplayer online battle arena desenvolvido e publicado pela Valve.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (15,    7,	"Dealock",						    "Valve",		            "Deadlock.png",						            0,		    9,			"Deadlock é um jogo de tiro em terceira pessoa e arena de batalha online multijogador desenvolvido e publicado pela Valve.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (16,    3,	"Portal",					        "Valve",				    "Portal.png",					                46.99,		10,			"Portal é uma série de jogos eletrônicos de primeira pessoa, com puzzles em plataforma desenvolvida por Valve Corporation.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (17,    3,	"Portal 2",						    "Valve",		            "Portal 2.png",						            49.99,		8.7,		"Portal 2 é um jogo eletrônico de quebra-cabeça em plataformas desenvolvido e publicado pela Valve Corporation");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (18,    7,	"Team Fortress 2",					"Valve",					"Team Fortress 2.png",					        0,		    10,			"Team Fortress 2 é um jogo eletrônico free-to-play multijogador de tiro em primeira pessoa desenvolvido pela Valve, baseado em equipes e com foco em combates.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (19,    2,	"Rayman Origins", 					"Ubisoft", 		            "Rayman Origins.png", 					        44.99,		10, 		"Rayman Origins é um jogo de plataforma 2D de 2011 que narra como Rayman, Globox e os Teensies precisam salvar a Clareira dos Sonhos.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (20,    3,	"FOR HONOR",					    "Ubisoft",					"For Honor.png",					            260,		8.7,	    "For Honor é um jogo de ação e luta corpo a corpo desenvolvido pela Ubisoft, ambientado em um mundo alternativo onde cavaleiros, vikings, samurais e outras facções guerreiras colidem em uma guerra perpétua.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (21,    8,	"Beyond Good & Evil",				"Ubisoft",				    "Beyond Good and Evil.png",				        27.50,		9.5,		"Beyond Good & Evil (2003) é um jogo de ação e aventura da Ubisoft onde a repórter Jade investiga uma conspiração alienígena no planeta Hillys.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (22,    3,	"The Crew Motorfest",				"Ubisoft",	                "The Crew Motor Fest.png",				        280,		9.7,	    "The Crew Motorfest é um jogo de corrida em mundo aberto desenvolvido pela Ivory Tower e publicado pela Ubisoft. A sinopse do jogo se concentra em um festival automotivo vibrante. ");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (23,    3,	"Star Wars Outlaws",				"Ubisoft",		            "Star Wars Outlaws.png",					    60,		    9,			"Star Wars Outlaws é um jogo de ação em mundo aberto ambientado entre O Império Contra-Ataca e O Retorno de Jedi.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (24,    2,	"South Park: The Stick of Truth",	"Ubisoft",				    "South Park the Stick of Truth.png",            46.99,		10,			"South Park: The Stick of Truth é um RPG satírico onde você controla o Novato, uma criança que se muda para a cidade e se envolve em uma guerra de RPG ao vivo entre as crianças locais");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (25,    3,	"Assassin's Creed 2",				"Ubisoft",		            "Assassin's Creed 2.png",				        49.99,		8.7,		"Assassin's Creed II é um jogo de ação e aventura ambientado na Renascença Italiana (1476-1499), onde o jovem nobre Ezio Auditore da Firenze busca vingança após a traição e execução de sua família.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (26,    8,	"Valiant Hearts: Coming Home",		"Ubisoft",			        "Valiant Hearts Coming Home.png",			    43.99,		8.8,		"Valiant Hearts: The Great War é um jogo de aventura e puzzle 2D da Ubisoft, ambientado na Primeira Guerra Mundial, que foca na narrativa emocionante de quatro personagens (e um cão fiel) cujos destinos se cruzam.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (27,    1,	"Resident Evil 4",					"Capcom",			        "Resident_Evil4.png",							125.99,		9.8,		"Leon S. Kennedy, segue o rastro da raptada filha do presidente até uma vila europeia isolada, onde há algo terrivelmente errado com os habitantes.");
INSERT INTO jogos(Id_jogo, id_categoria, Nome_jogo, desenvolvedora, imagem, valor, nota, detalhes) VALUE (28,    2,	"Albion Online",					"Sandbox Interactive",      "albion-online.jpg",							0,		    0,		    "Albion Online é um MMORPG sandbox em que você escreve sua própria história, em vez de seguir um caminho pré-determinado. Explore um vasto mundo aberto que consiste de 5 ecossistemas únicos.");



INSERT INTO categorias(id_categoria, nome_categoria) VALUE (1,	"Ação");
INSERT INTO categorias(id_categoria, nome_categoria) VALUE (2,	"RPG");
INSERT INTO categorias(id_categoria, nome_categoria) VALUE (3,	"3D");
INSERT INTO categorias(id_categoria, nome_categoria) VALUE (4,	"2D");
INSERT INTO categorias(id_categoria, nome_categoria) VALUE (5,	"Misterio");
INSERT INTO categorias(id_categoria, nome_categoria) VALUE (6,	"Indie");
INSERT INTO categorias(id_categoria, nome_categoria) VALUE (7,	"Shooter");
INSERT INTO categorias(id_categoria, nome_categoria) VALUE (8,	"Atmosferico");



INSERT INTO usuarios(id_usuario, nome_usuario, email_usuario, senha_usuario, administrador) VALUE (1,	"Adalberto Gomes",	    "adalberto@gamil",	"abc123",	    0);
INSERT INTO usuarios(id_usuario, nome_usuario, email_usuario, senha_usuario, administrador) VALUE (2,	"Borguinho Barros",	    "borguinho@gamil",	"def456",	    1);
INSERT INTO usuarios(id_usuario, nome_usuario, email_usuario, senha_usuario, administrador) VALUE (3,	"Carlos de Carvalho",	"carlos@gamil",		"ghi789",	    0);
INSERT INTO usuarios(id_usuario, nome_usuario, email_usuario, senha_usuario, administrador) VALUE (4,	"Daniel Denevtz",	    "daniel@gamil",		"jkl101112",	0);
INSERT INTO usuarios(id_usuario, nome_usuario, email_usuario, senha_usuario, administrador) VALUE (5,	"Emanuel Santos",	    "emanuel@gamil",	"mno131415",	0);
INSERT INTO usuarios(id_usuario, nome_usuario, email_usuario, senha_usuario, administrador) VALUE (6,	"Fabricio de Oliveira",	"fabricio@gamil",	"pqr161718",	0);
INSERT INTO usuarios(id_usuario, nome_usuario, email_usuario, senha_usuario, administrador) VALUE (7,	"Gilberto Gill",	    "gilberto@gamil",	"tuv192021",	0);
INSERT INTO usuarios(id_usuario, nome_usuario, email_usuario, senha_usuario, administrador) VALUE (8,	"Homero Barbosa",	    "homero@gamil",		"wxy222324",	0);
INSERT INTO usuarios(id_usuario, nome_usuario, email_usuario, senha_usuario, administrador) VALUE (9,	"Ivandro Costa",	    "ivandro@gamil",	"zAB252627",	0);
INSERT INTO usuarios(id_usuario, nome_usuario, email_usuario, senha_usuario, administrador) VALUE (10,	"Jeremias de Holanda",	"jeremias@gamil",	"CDE282930",	0);
